"""
Threat Feed Updater – scheduled download and parsing of threat intelligence lists.

Pulls data from:
  * Emerging Threats ``compromised-ips.txt`` (plain text)
  * Spamhaus DROP / EDROP lists (CIDR notation)
  * A configurable list of custom plain-text IP feeds

Feeds are written to the ``cache/`` directory consumed by
:class:`~threat_intelligence.threat_feed_manager.ThreatFeedManager`.

Usage (one-shot)::

    python -m threat_intelligence.updater

Usage (daemon)::

    python -m threat_intelligence.updater --daemon --interval 3600
"""

from __future__ import annotations

import argparse
import logging
import os
import sys
import time
from pathlib import Path
from typing import Any

import requests
import schedule
from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s  %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Feed definitions
# ---------------------------------------------------------------------------

_CACHE_DIR = Path(__file__).parent / "cache"

FEEDS: list[dict[str, Any]] = [
    {
        "name": "emerging_threats_compromised",
        "url": "https://rules.emergingthreats.net/blockrules/compromised-ips.txt",
        "output_file": "emerging_threats.txt",
        "format": "plain_ip",
    },
    {
        "name": "spamhaus_drop",
        "url": "https://www.spamhaus.org/drop/drop.txt",
        "output_file": "spamhaus_drop.txt",
        "format": "spamhaus",
    },
    {
        "name": "spamhaus_edrop",
        "url": "https://www.spamhaus.org/drop/edrop.txt",
        "output_file": "spamhaus_edrop.txt",
        "format": "spamhaus",
    },
]

# Additional feeds configurable via env (semicolon-separated URLs).
_EXTRA_FEEDS_ENV = os.getenv("EXTRA_THREAT_FEEDS", "")

_REQUEST_TIMEOUT: int = int(os.getenv("FEED_REQUEST_TIMEOUT", "30"))
_UPDATE_INTERVAL: int = int(os.getenv("FEED_UPDATE_INTERVAL", "3600"))


# ---------------------------------------------------------------------------
# Parsers
# ---------------------------------------------------------------------------

def _parse_plain_ip(content: str) -> list[str]:
    """
    Parse a plain-text file where each non-comment line is an IP or CIDR.

    Lines starting with ``#`` are skipped.
    """
    entries: list[str] = []
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        # Take only the first token (some files have trailing comments).
        token = line.split()[0]
        entries.append(token)
    return entries


def _parse_spamhaus(content: str) -> list[str]:
    """
    Parse Spamhaus DROP/EDROP format.

    Each data line looks like::

        1.2.3.0/24 ; SBL12345

    The CIDR block is the first field before the semicolon.
    """
    entries: list[str] = []
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith(";"):
            continue
        cidr = line.split(";")[0].strip()
        if cidr:
            entries.append(cidr)
    return entries


_PARSERS: dict[str, Any] = {
    "plain_ip": _parse_plain_ip,
    "spamhaus": _parse_spamhaus,
}


# ---------------------------------------------------------------------------
# Download & persist
# ---------------------------------------------------------------------------

def _download(url: str) -> str | None:
    """
    Download *url* and return its text content.

    Returns ``None`` on any network error (logged at WARNING level).
    """
    try:
        resp = requests.get(url, timeout=_REQUEST_TIMEOUT)
        resp.raise_for_status()
        return resp.text
    except requests.RequestException as exc:
        logger.warning("Failed to download %s: %s", url, exc)
        return None


def _write_cache(filename: str, entries: list[str]) -> Path:
    """Write *entries* (one per line) to ``cache/<filename>``."""
    _CACHE_DIR.mkdir(parents=True, exist_ok=True)
    out = _CACHE_DIR / filename
    with out.open("w") as fh:
        fh.write(f"# Auto-generated by updater.py – {len(entries)} entries\n")
        for entry in entries:
            fh.write(entry + "\n")
    logger.info("Wrote %d entries → %s", len(entries), out)
    return out


def _update_feed(feed: dict[str, Any]) -> bool:
    """
    Download, parse, and cache a single feed definition.

    Returns ``True`` on success, ``False`` on failure.
    """
    name = feed["name"]
    logger.info("Updating feed: %s", name)

    content = _download(feed["url"])
    if content is None:
        logger.error("Skipping feed %s (download failed)", name)
        return False

    parser = _PARSERS.get(feed.get("format", "plain_ip"), _parse_plain_ip)
    entries = parser(content)

    if not entries:
        logger.warning("Feed %s returned 0 entries – skipping write", name)
        return False

    _write_cache(feed["output_file"], entries)
    return True


def _update_all_feeds() -> dict[str, bool]:
    """
    Update every configured feed.

    Returns a mapping of feed name → success flag.
    """
    results: dict[str, bool] = {}

    all_feeds = list(FEEDS)
    if _EXTRA_FEEDS_ENV:
        for idx, url in enumerate(_EXTRA_FEEDS_ENV.split(";"), start=1):
            url = url.strip()
            if url:
                all_feeds.append(
                    {
                        "name": f"custom_{idx}",
                        "url": url,
                        "output_file": f"custom_feed_{idx}.txt",
                        "format": "plain_ip",
                    }
                )

    for feed in all_feeds:
        results[feed["name"]] = _update_feed(feed)

    successes = sum(results.values())
    logger.info(
        "Feed update complete: %d/%d succeeded", successes, len(all_feeds)
    )
    return results


# ---------------------------------------------------------------------------
# Scheduler
# ---------------------------------------------------------------------------

def _run_scheduled_updates(interval_seconds: int) -> None:
    """
    Run :func:`_update_all_feeds` immediately, then on *interval_seconds* cadence.

    Blocks indefinitely; use ``Ctrl-C`` or ``SIGTERM`` to stop.
    """
    logger.info("Starting scheduled updater (interval=%ds)", interval_seconds)

    # Perform an immediate update on start-up.
    _update_all_feeds()

    schedule.every(interval_seconds).seconds.do(_update_all_feeds)

    try:
        while True:
            schedule.run_pending()
            time.sleep(min(interval_seconds, 60))
    except KeyboardInterrupt:
        logger.info("Updater stopped by user")


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    """Parse CLI arguments and run the updater."""
    parser = argparse.ArgumentParser(
        description="Download and cache threat intelligence feeds",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--daemon",
        action="store_true",
        help="Run continuously on a schedule instead of a single update",
    )
    parser.add_argument(
        "--interval",
        type=int,
        default=_UPDATE_INTERVAL,
        metavar="SECONDS",
        help="Update interval when running as a daemon",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable DEBUG-level logging",
    )
    args = parser.parse_args(argv)

    if args.debug:
        logging.getLogger().setLevel(logging.DEBUG)

    if args.daemon:
        _run_scheduled_updates(args.interval)
        return 0

    results = _update_all_feeds()
    failed = [name for name, ok in results.items() if not ok]
    if failed:
        logger.error("Feeds that failed: %s", failed)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
